import { Router } from "express";
import { getConnectorsDebugAuth, getDerivDemoOAuthCallback, startDerivDemoOAuth } from "../controllers/connectorsController";
import { requireApiAuthJson, requireLicense } from "../middleware/authMiddleware";
import { authRoutes } from "./authRoutes";
import { backtestRoutes } from "./backtestRoutes";
import { connectorsRoutes } from "./connectorsRoutes";
import { demoObservationGateRoutes } from "./demoObservationGateRoutes";
import { executionRoutes } from "./executionRoutes";
import { journalRoutes } from "./journalRoutes";
import { licensesRoutes } from "./licensesRoutes";
import { marketDataRoutes } from "./marketDataRoutes";
import { realismAuditRoutes } from "./realismAuditRoutes";
import { riskRoutes } from "./riskRoutes";
import { shadowTradingRoutes } from "./shadowTradingRoutes";
import { signalsRoutes } from "./signalsRoutes";
import { statusRoutes } from "./statusRoutes";

export const apiRoutes = Router();

apiRoutes.use(statusRoutes);
apiRoutes.use(authRoutes);
apiRoutes.use(licensesRoutes);
apiRoutes.get("/connectors/debug-auth", getConnectorsDebugAuth);
apiRoutes.get("/connectors/deriv-demo/oauth/start", requireApiAuthJson(), startDerivDemoOAuth);
apiRoutes.get("/connectors/deriv-demo/oauth/callback", requireApiAuthJson(), getDerivDemoOAuthCallback);
apiRoutes.use(requireLicense());
apiRoutes.use(connectorsRoutes);
apiRoutes.use(marketDataRoutes);
apiRoutes.use(signalsRoutes);
apiRoutes.use(riskRoutes);
apiRoutes.use(backtestRoutes);
apiRoutes.use(executionRoutes);
apiRoutes.use(shadowTradingRoutes);
apiRoutes.use(realismAuditRoutes);
apiRoutes.use(demoObservationGateRoutes);
apiRoutes.use(journalRoutes);
